name: sparseconv
channels:
  - pytorch
  - nvidia
  - nvidia/label/cuda-11.7.0
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - cairo=1.16.0
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - cryptography=39.0.1
  - cuda-cccl=11.7.58
  - cuda-command-line-tools=11.7.0
  - cuda-compiler=11.7.0
  - cuda-cudart=11.7.99
  - cuda-cudart-dev=11.7.60
  - cuda-cuobjdump=11.7.50
  - cuda-cupti=11.7.101
  - cuda-cuxxfilt=11.7.50
  - cuda-documentation=11.7.50
  - cuda-driver-dev=11.7.60
  - cuda-gdb=11.7.50
  - cuda-libraries=11.7.1
  - cuda-libraries-dev=11.7.0
  - cuda-memcheck=11.7.50
  - cuda-nsight=11.7.50
  - cuda-nsight-compute=11.7.0
  - cuda-nvcc=11.7.64
  - cuda-nvdisasm=11.7.50
  - cuda-nvml-dev=11.7.50
  - cuda-nvprof=11.7.50
  - cuda-nvprune=11.7.50
  - cuda-nvrtc=11.7.99
  - cuda-nvrtc-dev=11.7.50
  - cuda-nvtx=11.7.91
  - cuda-nvvp=11.7.50
  - cuda-runtime=11.7.1
  - cuda-sanitizer-api=11.7.50
  - cuda-toolkit=11.7.0
  - cuda-tools=11.7.0
  - cuda-visual-tools=11.7.0
  - cudatoolkit=11.7.0
  - cudnn=8.4.1.50
  - expat=2.5.0
  - ffmpeg=4.3
  - fftw=3.3.9
  - fontconfig=2.14.2
  - freetype=2.12.1
  - gds-tools=1.3.0.44
  - giflib=5.2.1
  - glib=2.69.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - icu=70.1
  - idna=3.4
  - joblib=1.1.1
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.40
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcublas=11.10.3.66
  - libcublas-dev=11.10.1.25
  - libcufft=10.7.2.124
  - libcufft-dev=10.7.2.50
  - libcufile=1.6.1.9
  - libcufile-dev=1.3.0.44
  - libcurand=10.3.2.106
  - libcurand-dev=10.2.10.50
  - libcusolver=11.4.0.1
  - libcusolver-dev=11.3.5.50
  - libcusparse=11.7.4.91
  - libcusparse-dev=11.7.3.50
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=12.2.0
  - libiconv=1.16
  - libidn2=2.3.2
  - liblapack=3.9.0
  - libnpp=11.7.4.75
  - libnpp-dev=11.7.3.21
  - libnsl=2.0.0
  - libnvjpeg=11.8.0.2
  - libnvjpeg-dev=11.7.2.34
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libprotobuf=3.21.12
  - libsqlite=3.40.0
  - libstdcxx-ng=12.2.0
  - libtasn1=4.19.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxml2=2.9.14
  - libzlib=1.2.13
  - llvm-openmp=16.0.2
  - lz4-c=1.9.4
  - magma=2.6.2
  - mkl=2022.2.1
  - nccl=2.15.5.1
  - ncurses=6.3
  - nettle=3.7.3
  - ninja=1.10.2
  - ninja-base=1.10.2
  - nomkl=3.0
  - nsight-compute=2022.2.0.13
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openbabel=3.1.1
  - openblas-devel=0.3.21
  - openh264=2.1.1
  - openssl=3.1.0
  - pcre=8.45
  - pillow=9.4.0
  - pip=23.1.2
  - pixman=0.40.0
  - pthread-stubs=0.4
  - pycparser=2.21
  - pyopenssl=23.0.0
  - pysocks=1.7.1
  - python=3.10.10
  - python_abi=3.10
  - pytorch=1.13.0
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - readline=8.2
  - requests=2.29.0
  - scikit-learn=1.2.0
  - scipy=1.9.3
  - setuptools=67.7.2
  - sleef=3.5.1
  - tbb=2021.8.0
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - torchvision=0.14.0
  - typing_extensions=4.5.0
  - tzdata=2023c
  - urllib3=1.26.15
  - wheel=0.40.0
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - zlib=1.2.13
  - zstd=1.5.2
